### PR TITLE
Transfer id to geojson file when id found in topojson

### PR DESCRIPTION
**Pull request by caticoa3**
ID is typically an import piece of information, for example it could be a FIPS code. 
What do you think about transferring over the id?

### CODE REVIEW

**Comment by kylepollina** [comment]
I think this is a good idea. If you could provide an example and maybe a screenshot with this working correctly I'd be glad to merge.

**Comment by caticoa3** [comment]
cool, here is an example with a screenshot
```
curl -o colombia.topojson https://gist.githubusercontent.com/john-guerra/727e8992e9599b9d9f1dbfdc4c8e479e/raw/090f8b935a437e24d65b64d87598fbb437c006da/colombia-municipios.json
topo2geo colombia.topojson colombia.geojson
```
then comparing (topojson on the left) we see the id trasfered to the geojson file:

image

**Review by kylepollina — APPROVED** [review]

**Comment by kylepollina** [comment]
I accidentally reverted/overwrote these changes after I merged, so I re-added them back into the source code.

**Comment by caticoa3** [comment]
Doesn't that essentially remove me as a contributor from the repo? My commits then no longer in the history.

**Comment by kylepollina** [comment]
Oh yeah, you are right. I could remove them and then you can try another pull request? Sorry, I've never had anyone contribute to a project of mine before, I'm new to this. But I'd like to get you back in the contributors list

**Comment by kylepollina** [comment]
Okay, I've reverted the changes, you are free to open the pull request again!

**Comment by caticoa3** [comment]
OK. No problem. Github has some intricacies, and I am no master of those intricacies either. :)
Here is the PR that is relevant to this branch:
https://github.com/kylepollina/topo2geo/pull/4
I also made another PR that addresses conversion of multilayered topojsons
https://github.com/kylepollina/topo2geo/pull/3

**Comment by kylepollina** [comment]
Awesome. Merged #4 back into master, I will be taking a look at #3

**Pull request merged**
